// models/Project.js
const mongoose = require("mongoose");

const projectSchema = new mongoose.Schema(
  {
    projectName: {
      type: String,
      required: true,
      trim: true,
    },
   
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User", // reference to User model
      required: true,
    },
    // author: {
    //   type: String,
    //   required: true,
    // },
    techStack: [
      {
        type: String, // filled by ML model
      },
    ],
    questions: [
      {
        question: { type: String }, // generated by ML
        createdAt: { type: Date, default: Date.now },
      },
    ],

    //  Source type: either "github" or "zip"
    sourceType: {
      type: String,
      enum: ["github", "zip"],
      required: true,
    },

    //  For GitHub uploads
    githubLink: {
      type: String,
      trim: true,
    },

    //  For ZIP uploads
    zipFilePath: {
      type: String, // stores local file path
      trim: true,
    },

    //  Optional deployed link
    deployedLink: {
      type: String,
      trim: true,
    },
  },
  { timestamps: true } // adds createdAt & updatedAt
);

module.exports = mongoose.model("Project", projectSchema);
